### ISSUE TITLE
Defining version 17 stops the shortcut from being signed successfully

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#34]
**Describe the bug**
When I define version 17, the generated .plist file is invalid. It causes an error when a sign is attempted: 
```
Signing main_unsigned.shortcut to main.shortcut...
failed!

Error: Failed to sign Shortcut

shortcuts: Error: The data couldn’t be read because it isn’t in the correct format.
```

**To Reproduce**
The code to reproduce your issue if applicable:

```ruby
#define version 17

alert("Hello World!")
```

**Debug output**
```
Parsing main.cherri...
### PARSING ###

Previous Character:
) 3:21

Current Character:
EMPTY 3:21

Current Line:
alert("Hello World!")
## TOKENS ##
1 | {action alert action {alert [{text Hello World!}]}}

## DEFINITIONS ##
Name: main
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 2038.0.2.4
iOS Version: 17.0

## VARIABLES ##

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

Done.

Generating plist...
### PLIST GEN ###

## UUIDS ##
map[]

Done.

Writing to main.plist...
Done.

Writing to main_unsigned.shortcut...
Done.

Signing main_unsigned.shortcut to main.shortcut...
failed!

Error: Failed to sign Shortcut

shortcuts: Error: The data couldn’t be read because it isn’t in the correct format.


###################
#   DEBUG PANIC   #
###################

### PARSING ###

Previous Character:
EMPTY 1:0

Current Character:
EMPTY 1:0

## TOKENS ##

## DEFINITIONS ##
Name: main
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 2038.0.2.4
iOS Version: 17.0

## VARIABLES ##

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

### PLIST GEN ###

## UUIDS ##
map[]

### CUSTOM ACTIONS ###


### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

#############################################################

panic: debug

goroutine 1 [running]:
main.panicDebug({0x0, 0x0})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:320 +0x12c
main.exit({0x140001a4080?, 0x102bceea5?})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:393 +0x10c
main.sign()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:227 +0x78c
main.createShortcut()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:149 +0x280
main.main()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:79 +0x364
```

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Additional context**
N/A

**Comment by electrikmilk** [comment]
Thanks for calling this out! This is fixed by [4ea3fff](https://github.com/electrikmilk/cherri/commit/4ea3fff97a6aba4d5202b7be81defd572ba74f14).
