### ISSUE TITLE
`killApp`, `openApp`, `quitApp`, `hideApp`, and `splitApps` cause the compiler to crash when used with a variable.

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#37]
**To Reproduce**
```ruby
@e = "com.apple.mobilesafari"
quitApp(e)
```
```ruby
@e = "com.apple.mobilesafari"
openApp(e)
```
```ruby
@e = "com.apple.mobilesafari"
killApp(e)
```
```ruby
@e = "com.apple.mobilesafari"
hideApp(e)
```
```ruby
@e = "com.apple.mobilesafari"
@a = "com.apple.mail"
@s = "half"
splitApps(e, a, s)
```

**Debug output**
```
Parsing test.cherri...
### PARSING ###

Previous Character:
) 2:10

Current Character:
EMPTY 2:10

Current Line:
quitApp(e)
## TOKENS ##
1 | {variable e text com.apple.mobilesafari}
2 | {action quitApp action {quitApp [{variable com.apple.mobilesafari}]}}

## DEFINITIONS ##
Name: test
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 900
iOS Version: 17.0

## VARIABLES ##
@e = com.apple.mobilesafari (text)

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

Done.

Generating plist...

Error: Undefined reference 'com'

###################
#   DEBUG PANIC   #
###################

### PARSING ###

Previous Character:
EMPTY 1:0

Current Character:
EMPTY 1:0

## TOKENS ##
1 | {variable e text com.apple.mobilesafari}
2 | {action quitApp action {quitApp [{variable com.apple.mobilesafari}]}}

## DEFINITIONS ##
Name: test
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 900
iOS Version: 17.0

## VARIABLES ##
@e = com.apple.mobilesafari (text)

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

### PLIST GEN ###

## UUIDS ##
map[e:AE878BDA-B8A6-4FDA-90FC-FD68D8963B0A]

### CUSTOM ACTIONS ###


### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

#############################################################

panic: debug

goroutine 1 [running]:
main.panicDebug({0x0, 0x0})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:320 +0x12c
main.exit({0x140000de2e0?, 0x18?})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:393 +0x10c
main.makeAttachmentValues()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plist.go:634 +0x2b8
main.attachmentValues({0x104f07d2a, 0x10}, {0x140000b4180, 0x18}, {0x104f030c0, 0x6})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plist.go:593 +0x11c
main.paramValue({0x104f07d2a, 0x10}, {{0x104f03bfd?, 0x7?}, {0x104f4d600?, 0x140000a2140?}}, {0x104f0282f?, 0x104de4d20?}, {0x104f030c0?, 0x400000?})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plist.go:821 +0x154
main.argumentValue({0x104f07d2a, 0x10}, {0x140000c6220, 0x1, 0x200?}, 0x0)
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plist.go:811 +0x310
main.scriptingActions.func32({0x140000c6220?, 0x140000a64e0?, 0x140000b0130?})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/actions_std.go:3418 +0x40
main.actionParameters({0x140000c6220?, 0x1, 0x1})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/action.go:124 +0x26c
main.plistAction({0x140000c6220, 0x1, 0x1}, 0x14000125708, 0x140001256d8)
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/action.go:92 +0x68
main.plistActions()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plistgen.go:178 +0x3b8
main.makePlist()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/plistgen.go:36 +0x244
main.main()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:77 +0x360
```

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Comment by electrikmilk** [comment]
We were not properly handling variables and were just expecting string values. This is fixed by [13c1147](https://github.com/electrikmilk/cherri/commit/13c1147492dfba23d3c25db10a1866580e4c9f03).
