### ISSUE TITLE
Unable to stop and give a response when input isn't provided

### ISSUE THREAD

**Issue by mikeogezi** [electrikmilk/cherri#40]
**Describe the bug**
The compiler errors out when we use the syntax: `#define noinput stopwith "..."`

**To Reproduce**
```ruby
#define noinput stopwith "Response"

alert("Hello World")
```

**Debug output**
```
Parsing test.cherri...

Undefined action 'Response()'

----- test.cherri:1:36
1 | 
                                       ^
2 | #define noinput stopwith "Response"
-----

###################
#   DEBUG PANIC   #
###################

### PARSING ###

Previous Character:
e 1:35

Current Character:
" 1:35

Next Character:
a 1:35

Current Line:

## TOKENS ##

## DEFINITIONS ##
Name: test
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: {WFWorkflowNoInputBehaviorShowError [{Error string }]}
macOS Only: false
Mininum Version: 900
iOS Version: 17.0

## VARIABLES ##

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

### PLIST GEN ###

## UUIDS ##
map[]

### CUSTOM ACTIONS ###


### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

#############################################################

panic: debug

goroutine 1 [running]:
main.panicDebug({0x0, 0x0})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:320 +0x12c
main.parserError({0x1400001e0c0, 0x1d})
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/parser.go:1401 +0x2a0
main.collectAction()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/parser.go:1179 +0xb0
main.collectActionCall()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/parser.go:1164 +0x24
main.parse()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/parser.go:166 +0x420
main.initParse()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/parser.go:49 +0x2f4
main.main()
        /Users/michaelogezi/go/pkg/mod/github.com/electrikmilk/cherri@v0.1.11-beta.0.20231203021550-d1a03f308510/main.go:75 +0x35c
```

**Version Information (please complete the following information):**
 - macOS version (run `uname -a`): Darwin Michaels-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Fri Oct 13 09:28:08 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T8112 arm64
 - Golang version (run `go version`): go version go1.21.4 darwin/arm64

**Comment by electrikmilk** [comment]
We were not advancing past the opening double quote, and so `collectString()` saw that double quote and thought it was the end of the string and exited instead of collecting the string.

This is now fixed by [feb0bb1](https://github.com/electrikmilk/cherri/commit/feb0bb1d0ce14aa569195f73ac3f5e3b522af20c).
