### ISSUE TITLE
Custom actions can't use constants declared outside of them

### ISSUE THREAD

**Issue by NoelTautges** [electrikmilk/cherri#60]
**Describe the bug**

Custom actions can't use constants declared outside of them, even if they were declared before them.

**To Reproduce**

```ruby
const global = "Testing!"

action test() {
	alert(global)
}

test()
```

**Debug output**

```
Parsing global_vars.cherri...
Parsing includes...
### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

Done.

### CUSTOM ACTIONS ###

identifier: test()
used: true
parameters:
[]
body:
alert(global)
(end)

if ShortcutInput {
    const _cherri_inputType = typeOf(ShortcutInput)
    if _cherri_inputType == "Dictionary" {
        const _cherri_input = getDictionary(ShortcutInput)
        const _cherri_identifier = getValue(_cherri_input, "cherri_functions")
        const _cherri_valid = number(_cherri_identifier)
        if _cherri_valid == true {
            const _cherri_function = getValue(_cherri_input, "function")
            const _cherri_function_name = "{_cherri_function}"
            const _cherri_function_args = getValue(_cherri_input, "arguments")
            if _cherri_function_name == "test" {
alert(global)
output(nil)
            }
            output(nil)
        }
    }
}
const global = "Testing!"





test()


Undefined reference 'global'

----- global_vars.cherri:12:14
11 |             if _cherri_function_name == "test" {
12 | alert(global)
                 ^
13 | output(nil)
-----

###################
#   DEBUG PANIC   #
###################

### PARSING ###

Previous Character:
l 12:13

Current Character:
) 12:13

Next Character:
o 12:13

Current Line:
alert(global)
## TOKENS ##
 1 | {conditional 94f12b15-e422-46ca-9e47-d4090bbefd6f if {variable ShortcutInput 100  <nil>  <nil>}}
 2 | {variable _cherri_inputType action {typeOf [{variable ShortcutInput}]}}
 3 | {conditional d62d9be5-3be6-44a8-9bd6-1320f320d13e if {variable _cherri_inputType 4 text Dictionary  <nil>}}
 4 | {variable _cherri_input action {getDictionary [{variable ShortcutInput}]}}
 5 | {variable _cherri_identifier action {getValue [{variable _cherri_input} {text cherri_functions}]}}
 6 | {variable _cherri_valid action {number [{variable _cherri_identifier}]}}
 7 | {conditional c5105c23-3ae8-4d6b-9805-fcaa882a8a90 if {variable _cherri_valid 4 bool %!s(bool=true)  <nil>}}
 8 | {variable _cherri_function action {getValue [{variable _cherri_input} {text function}]}}
 9 | {variable _cherri_function_name text {_cherri_function}}
10 | {variable _cherri_function_args action {getValue [{variable _cherri_input} {text arguments}]}}
11 | {conditional c56df374-fbd3-41d9-b017-ccf6f6728504 if {variable _cherri_function_name 4 text test  <nil>}}

## DEFINITIONS ##
Name: global_vars
Color: -1263359489
Glyph: 61440
Inputs: []
Outputs: []
Workflows: []
No Input: { []}
macOS Only: false
Mininum Version: 2106.0.3
iOS Version: 17.0

## VARIABLES ##
const _cherri_inputType = {typeOf [{variable ShortcutInput}]} (action)
const _cherri_input = {getDictionary [{variable ShortcutInput}]} (action)
const _cherri_identifier = {getValue [{variable _cherri_input} {text cherri_functions}]} (action)
const _cherri_valid = {number [{variable _cherri_identifier}]} (action)
const _cherri_function = {getValue [{variable _cherri_input} {text function}]} (action)
const _cherri_function_name = {_cherri_function} (text)
const _cherri_function_args = {getValue [{variable _cherri_input} {text arguments}]} (action)

## MENUS ##
map[]

## IMPORT QUESTIONS ##
map[]

### PLIST GEN ###

## UUIDS ##
map[]

### CUSTOM ACTIONS ###

identifier: test()
used: true
parameters:
[]
body:
alert(global)
(end)

### INCLUDES ###

## INCLUDED ##
[]

## INCLUDES MAP ##
[]

#############################################################

panic: debug

goroutine 1 [running]:
main.panicDebug({0x0, 0x0})
        [snip]/cherri/main.go:193 +0x14d
main.parserError({0xc0001666c0, 0x1c})
        [snip]/cherri/parser.go:1505 +0x2c5
main.collectReference(0xc000031510, 0xc000031520, 0xc0000314b0)
        [snip]/cherri/parser.go:383 +0x34a
main.collectValue(0xc00016d510, 0xc00016d520, 0x29)
        [snip]/cherri/parser.go:319 +0x6a6
main.collectArgument(0xc00016d610?, 0xc000031600, 0x0?)
        [snip]/cherri/parser.go:446 +0x25e
main.collectArguments()
        [snip]/cherri/parser.go:420 +0x125
main.collectAction(0xc000031798)
        [snip]/cherri/parser.go:1267 +0x1d8
main.collectActionCall()
        [snip]/cherri/parser.go:1251 +0x252
main.parse()
        [snip]/cherri/parser.go:175 +0x398
main.initParse()
        [snip]/cherri/parser.go:66 +0x3b3
main.main()
        [snip]/cherri/main.go:76 +0x3db
```

**Expected behavior**

I expected the custom action to be able to use the shortcut as a kind of global variable that doesn't require user interaction or anything.

**Version Information:**
 - Linux version: `Linux cs-171148009998-default 6.1.77+ #1 SMP PREEMPT_DYNAMIC Sat May  4 16:42:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
 - Golang version: `go version go1.22.3 linux/amd64`

**Additional context**

I... don't really have a firm idea what would be done to fix this issue. It makes sense why it happens (all the custom actions get hoisted into a template at the beginning of the Shortcut, above where the constant is defined).

The main thing I can think of is to hoist all global constants, or perhaps only ones referenced in custom actions, that don't depend on user interaction even farther up.

If this is just a Not Gonna Put Myself Through That thing, feel free to close the issue. If you're open to the above solution, then I can try to put in a PR.

**Comment by electrikmilk** [comment]
This is partially difficult due to Shortcuts being very procedural and so it helps if the compiler works the same. It doesn't know all of the variables or constants until it comes across them one by one just like Shortcuts.

So to accomplish this, we would need to first collect all of the constants and their values before building out the tokens of the actual Shortcut. Constants are not locked variables, they are magic variables, references to actions, and so we would need to collect their parser token to recreate the action being referenced and even then technically speaking it would not be referencing the same action.

The custom actions template would likely need to be refactored to add parser tokens rather than strings, before the main parsing loop.

I implemented custom actions to have their own scope isolated from the global context, with the [Copy/Paste](https://cherrilang.org/language/copy-paste.html) feature meant for when you needed to reuse actions but retain the global context.

I don't think this is a bad idea, but I'm not sure if it is worth the effort.
